
spring:
  # 配置数据源（暂时就单数据源）
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
      dynamic:
        primary: iot
        datasource:
          iot:
            url: jdbc:mysql://localhost:3309/ziyun-iot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
            username: ziyun
            password: Pass1234
          cloud:
            url: jdbc:mysql://localhost:3309/ziyun-iot-cloud?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
            username: ziyun
            password: Pass1234
          idm:
            url: jdbc:mysql://localhost:3309/ziyun-idm?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
            username: ziyun
            password: Pass1234
          finance:
            url: jdbc:mysql://localhost:3309/ziyun-finance?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
            username: ziyun
            password: Pass1234

idm2:
  url: https://www.ziyun-cloud.com/service/idm
  clientId: 2tnM4URCkEjAFvvTp3
  clientSecret: vKFBpQOacmuRAhWOHvNM
  userName: 金融开发者账号
  password: 123456
  grantType: password
  ssoId: ZY001759516221